CREATE TABLE IF NOT EXISTS clients (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(200) NOT NULL CHECK (LENGTH(name) BETWEEN 3 AND 200)
);

CREATE TABLE IF NOT EXISTS planets (
	id VARCHAR(10) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
	name VARCHAR(500) NOT NULL CHECK (LENGTH(name) BETWEEN 1 AND 500)
);

CREATE TABLE IF NOT EXISTS tickets (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	created_at DATE NOT NULL,
	client_id BIGINT NOT NULL REFERENCES clients(id),
	from_planet_id VARCHAR(10) NOT NULL REFERENCES planets(id),
	to_planet_id VARCHAR(10) NOT NULL REFERENCES planets(id)
);